// Shared Monaco theme used by both the input Editor (CodeEditor) and the
// review's DiffEditor (DiffViewer). Lives here so both components register
// the same theme and the visual stays consistent edge-to-edge.
//
// Note: we don't type this against `editor.IStandaloneThemeData` because
// `monaco-editor` isn't a direct dependency (only `@monaco-editor/react`
// is). The shape is structurally validated where `defineTheme` is called.

export const INFERLOOP_MONO_THEME = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: '',                       foreground: 'e4e4e7' },
        { token: 'comment',                foreground: '6b7280', fontStyle: 'italic' },
        { token: 'keyword',                foreground: 'c4b5fd' },
        { token: 'keyword.control',        foreground: 'c4b5fd' },
        { token: 'keyword.operator',       foreground: 'd4d4d8' },
        { token: 'string',                 foreground: 'fda4af' },
        { token: 'string.escape',          foreground: 'fbcfe8' },
        { token: 'number',                 foreground: 'fdba74' },
        { token: 'regexp',                 foreground: 'a7f3d0' },
        { token: 'type',                   foreground: 'a5b4fc' },
        { token: 'type.identifier',        foreground: 'a5b4fc' },
        { token: 'class',                  foreground: 'a5b4fc' },
        { token: 'interface',              foreground: 'a5b4fc' },
        { token: 'function',               foreground: '93c5fd' },
        { token: 'entity.name.function',   foreground: '93c5fd' },
        { token: 'identifier',             foreground: 'e4e4e7' },
        { token: 'identifier.function',    foreground: '93c5fd' },
        { token: 'variable',               foreground: 'e4e4e7' },
        { token: 'variable.parameter',     foreground: 'fde68a' },
        { token: 'constant',               foreground: 'fdba74' },
        { token: 'constant.numeric',       foreground: 'fdba74' },
        { token: 'constant.language',      foreground: 'fdba74' },
        { token: 'operator',               foreground: 'd4d4d8' },
        { token: 'delimiter',              foreground: 'a1a1aa' },
        { token: 'delimiter.bracket',      foreground: 'a1a1aa' },
        { token: 'tag',                    foreground: 'fda4af' },
        { token: 'attribute.name',         foreground: 'c4b5fd' },
        { token: 'attribute.value',        foreground: 'fda4af' },
        { token: 'metatag',                foreground: 'fda4af' },
        { token: 'annotation',             foreground: 'c4b5fd' },
        { token: 'emphasis',               fontStyle: 'italic' },
        { token: 'strong',                 fontStyle: 'bold' },
    ],
    colors: {
        'editor.background':                   '#18181b',
        'editor.foreground':                   '#e4e4e7',
        'editorLineNumber.foreground':         '#3f3f46',
        'editorLineNumber.activeForeground':   '#a1a1aa',
        'editorCursor.foreground':             '#fafafa',
        'editor.selectionBackground':          '#ffffff15',
        'editor.inactiveSelectionBackground':  '#ffffff08',
        'editor.lineHighlightBackground':      '#ffffff05',
        'editor.lineHighlightBorder':          '#ffffff00',
        'editorIndentGuide.background1':       '#27272a',
        'editorIndentGuide.activeBackground1': '#3f3f46',
        'editorWhitespace.foreground':         '#27272a',
        'editorBracketMatch.background':       '#ffffff10',
        'editorBracketMatch.border':           '#ffffff30',
        'editor.findMatchBackground':          '#fde68a40',
        'editor.findMatchHighlightBackground': '#fde68a20',
        'scrollbarSlider.background':          '#ffffff10',
        'scrollbarSlider.hoverBackground':     '#ffffff20',
        'scrollbarSlider.activeBackground':    '#ffffff30',
        'minimap.background':                  '#18181b',
        'minimapSlider.background':            '#ffffff10',
        'minimapSlider.hoverBackground':       '#ffffff20',
        'editorWidget.background':             '#18181b',
        'editorWidget.border':                 '#27272a',
        'editorGutter.background':             '#18181b',
        'editorSuggestWidget.background':      '#18181b',
        'editorSuggestWidget.border':          '#27272a',
        'editorSuggestWidget.foreground':      '#e4e4e7',
        'editorSuggestWidget.selectedBackground': '#ffffff10',
        'editorHoverWidget.background':        '#18181b',
        'editorHoverWidget.border':            '#27272a',
        'editorBracketHighlight.foreground1':  '#c4b5fd',
        'editorBracketHighlight.foreground2':  '#93c5fd',
        'editorBracketHighlight.foreground3':  '#a7f3d0',
        'editorBracketHighlight.foreground4':  '#fdba74',
        'editorBracketHighlight.foreground5':  '#fda4af',
        'editorBracketHighlight.foreground6':  '#a5b4fc',
        'editorBracketHighlight.unexpectedBracket.foreground': '#fda4af',
        // Diff-specific colors — soft red for removed lines, soft emerald for
        // added lines. Same desaturated palette as the rest of the theme so
        // the diff still feels muted rather than alarming.
        'diffEditor.removedTextBackground':     '#fda4af26',
        'diffEditor.insertedTextBackground':    '#a7f3d022',
        'diffEditor.removedLineBackground':     '#fda4af12',
        'diffEditor.insertedLineBackground':    '#a7f3d012',
        'diffEditorGutter.removedLineBackground':  '#fda4af18',
        'diffEditorGutter.insertedLineBackground': '#a7f3d018',
        'diffEditorOverview.removedForeground':  '#fda4af80',
        'diffEditorOverview.insertedForeground': '#a7f3d080',
        'diffEditor.diagonalFill':              '#27272a55',
    },
};

// Internal language → Monaco language ID mapping. Shared between Editor and
// DiffEditor so a single change updates both surfaces.
export const LANGUAGE_TO_MONACO: Record<string, string> = {
    javascript: 'javascript',
    typescript: 'typescript',
    python:     'python',
    go:         'go',
    rust:       'rust',
    java:       'java',
    cpp:        'cpp',
};
